import { Orelega_One } from 'next/font/google'
import "./globals.css";

const orelega = Orelega_One({ 
  subsets: ['latin'],
  weight: ['400'],  // Orelega One only comes in weight 400
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={orelega.className}>
      <body className="container mx-auto">
        {children}
      </body>
    </html>
  );
}
